-- Phase 1 intentionally does not seed application users or production-like data.
-- Auth.js credential hashes and role relationships must come from an approved,
-- an explicitly reviewed export rather than committed fixtures.
