"use client";

import { useEffect, useMemo, useState, useTransition, type FormEvent } from "react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Dialog } from "radix-ui";
import { ArrowDownAZ, ArrowUpAZ, Check, ChevronLeft, ChevronRight, Mail, MessageSquareText, Phone, Search, ShieldCheck, Trash2, UserRoundPlus, Users, X } from "lucide-react";

import { approveLeadAsClient, deleteLead } from "@/app/actions/admin-leads";
import type { AdminLeadRecord, AdminLeadStatus } from "@/lib/dashboard/admin-dashboard-data";
import { paginateDashboardItems } from "@/lib/dashboard/pagination";
import type { AdminLeadInitialOption } from "@/lib/repositories/admin-lead-repository";
import styles from "./admin-leads-workspace.module.css";

type Props = { records: AdminLeadRecord[]; searchValue: string; selectedInitial: string | null; sortOrder: "asc" | "desc"; currentPage: number; totalCount: number; filteredCount: number; initialOptions: AdminLeadInitialOption[] };

function stateClass(status: AdminLeadStatus) { if (status === "New") return styles.red; if (status === "Converted") return styles.success; if (status === "Closed") return styles.neutral; return styles.warning; }

export function AdminLeadsWorkspace({ records, searchValue, selectedInitial, sortOrder, currentPage, totalCount, filteredCount, initialOptions }: Props) {
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams();
  const [pending, startTransition] = useTransition();
  const [search, setSearch] = useState(searchValue);
  const [status, setStatus] = useState<"All" | AdminLeadStatus>("All");
  const [selectedId, setSelectedId] = useState(records[0]?.id ?? "");
  const [deleteLeadRecord, setDeleteLeadRecord] = useState<AdminLeadRecord | null>(null);
  const [message, setMessage] = useState("");
  const [credentials, setCredentials] = useState<{ clientId: string; temporaryPassword: string; details: string } | null>(null);

  useEffect(() => setSearch(searchValue), [searchValue]);
  const visible = useMemo(() => records.filter((lead) => status === "All" || lead.status === status), [records, status]);
  const paginated = paginateDashboardItems(visible, currentPage);
  const selected = visible.find((lead) => lead.id === selectedId) ?? visible[0] ?? null;
  const pendingCount = records.filter((lead) => !["Converted", "Closed"].includes(lead.status)).length;

  function updateQuery(updates: Record<string, string | null>) { const params = new URLSearchParams(searchParams.toString()); Object.entries(updates).forEach(([key, value]) => value ? params.set(key, value) : params.delete(key)); const query = params.toString(); startTransition(() => router.replace(query ? `${pathname}?${query}` : pathname, { scroll: false })); }
  function submitSearch(event: FormEvent) { event.preventDefault(); updateQuery({ q: search.trim() || null, page: null }); }
  function approve(lead: AdminLeadRecord) { setMessage(""); setCredentials(null); startTransition(async () => { try { const summary = await approveLeadAsClient(lead.id); const promoted = summary.results.find((result) => result.outcome === "promoted"); if (promoted?.clientId && promoted.temporaryPassword) setCredentials({ clientId: promoted.clientId, temporaryPassword: promoted.temporaryPassword, details: promoted.details }); setMessage(promoted?.details ?? "Request approved as client."); router.refresh(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Approval failed."); } }); }
  function remove() { if (!deleteLeadRecord) return; setMessage(""); startTransition(async () => { try { await deleteLead(deleteLeadRecord.id); setMessage(`Deleted request for ${deleteLeadRecord.fullName}.`); setDeleteLeadRecord(null); router.refresh(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Delete failed."); } }); }

  return <div className={styles.page} aria-busy={pending}>
    <header className={styles.hero}><div><span className={styles.kicker}>Join intake</span><h1>Choose who joins.</h1><p>Review every request as a complete person, make the decision, then hand over secure access.</p></div><Link href="/admin/clients" className="mv-btn mv-btn-secondary"><Users size={17} /> Member directory</Link></header>
    <section className={styles.scoreboard} aria-label="Join request summary"><article><span>Total requests</span><strong>{totalCount}</strong><small>{filteredCount} match server filters</small></article><article><span>Decision queue</span><strong>{pendingCount}</strong><small>New or contacted requests</small></article><article><span>New arrivals</span><strong>{records.filter((lead) => lead.status === "New").length}</strong><small>Untouched requests</small></article><article className={styles.blackCard}><span>Converted</span><strong>{records.filter((lead) => lead.status === "Converted").length}</strong><small>Client accounts created</small></article></section>
    <section className={styles.queue}>
      <div className={styles.controls}><form className={styles.search} onSubmit={submitSearch}><Search size={17} /><label className="sr-only" htmlFor="lead-search">Search requests</label><input id="lead-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name, phone, source or message" /><button type="submit" disabled={pending}>Search</button></form><div className={styles.statuses}>{(["All", "New", "Converted", "Closed"] as const).map((item) => <button type="button" key={item} data-active={status === item || undefined} onClick={() => setStatus(item)}>{item}</button>)}</div><button type="button" className={styles.sort} aria-label={`Sort ${sortOrder === "asc" ? "descending" : "ascending"}`} onClick={() => updateQuery({ sort: sortOrder === "asc" ? "desc" : null, page: null })}>{sortOrder === "asc" ? <ArrowDownAZ size={18} /> : <ArrowUpAZ size={18} />}</button></div>
      <div className={styles.initials}><button type="button" data-active={!selectedInitial || undefined} onClick={() => updateQuery({ initial: null, page: null })}>All</button>{initialOptions.map((item) => <button type="button" key={item.label} data-active={selectedInitial === item.label || undefined} onClick={() => updateQuery({ initial: selectedInitial === item.label ? null : item.label, page: null })}>{item.label}<small>{item.count}</small></button>)}</div>
      {message ? <p className={styles.notice} role="status">{message}</p> : null}
      <div className={styles.queueGrid}><section className={styles.leadList} aria-label="Join request queue"><div className={styles.sectionTitle}><div><span>Decision queue</span><h2>{visible.length} requests in view</h2></div><small>Select a request</small></div>{paginated.items.length ? <div>{paginated.items.map((lead) => <button type="button" key={lead.id} data-selected={selected?.id === lead.id || undefined} onClick={() => setSelectedId(lead.id)}><span className={styles.avatar}>{lead.fullName.split(/\s+/).slice(0,2).map((part) => part[0]).join("")}</span><span className={styles.identity}><strong>{lead.fullName}</strong><small>{lead.source} · {lead.createdAt}</small></span><span className={`${styles.state} ${stateClass(lead.status)}`}>{lead.status}</span><ChevronRight size={17} /></button>)}</div> : <div className={styles.empty}><Search size={24} /><strong>No requests match</strong><span>Change the filters to reopen the queue.</span></div>}<footer className={styles.pagination}><span>Showing {paginated.startItem}-{paginated.endItem} of {paginated.totalItems}</span><div><button disabled={paginated.page <= 1} onClick={() => updateQuery({ page: String(paginated.page - 1) })}><ChevronLeft size={16} /></button><strong>{paginated.page}/{paginated.pageCount}</strong><button disabled={paginated.page >= paginated.pageCount} onClick={() => updateQuery({ page: String(paginated.page + 1) })}><ChevronRight size={16} /></button></div></footer></section>
        <aside className={styles.dossier}>{selected ? <><div className={styles.dossierHead}><span className={styles.bigAvatar}>{selected.fullName.split(/\s+/).slice(0,2).map((part) => part[0]).join("")}</span><div><span className={`${styles.state} ${stateClass(selected.status)}`}>{selected.status}</span><h2>{selected.fullName}</h2><small>Submitted {selected.createdAt} via {selected.source}</small></div></div><div className={styles.contact}><a href={`mailto:${selected.email}`}><Mail size={15} /> {selected.email}</a><a href={`tel:${selected.phone}`}><Phone size={15} /> {selected.phone}</a></div><section className={styles.message}><MessageSquareText size={18} /><div><span>Why they want to join</span><p>{selected.message || "No message was included with this request."}</p></div></section>{selected.status === "Converted" ? <div className={styles.converted}><ShieldCheck size={20} /><div><strong>Client account created</strong><span>This request has completed intake.</span></div></div> : <div className={styles.decisions}><button type="button" className="mv-btn mv-btn-primary" disabled={pending} onClick={() => approve(selected)}><UserRoundPlus size={17} /> {pending ? "Approving…" : "Approve & create client"}</button><button type="button" className={styles.deleteButton} disabled={pending} onClick={() => setDeleteLeadRecord(selected)}><Trash2 size={16} /> Delete request</button></div>}</> : <div className={styles.empty}><Users size={25} /><strong>No request selected</strong></div>}</aside>
      </div>
    </section>
    <Dialog.Root open={!!deleteLeadRecord} onOpenChange={(open) => !open && setDeleteLeadRecord(null)}><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.confirm}><Dialog.Title>Delete this request?</Dialog.Title><Dialog.Description>{deleteLeadRecord ? `${deleteLeadRecord.fullName} will be removed from the intake queue and database.` : "This request will be removed."}</Dialog.Description><Dialog.Close className={styles.close} aria-label="Close confirmation"><X size={18} /></Dialog.Close><div><button className="mv-btn mv-btn-secondary" onClick={() => setDeleteLeadRecord(null)}>Cancel</button><button className={styles.deleteButton} onClick={remove} disabled={pending}>Confirm delete</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
    <Dialog.Root open={!!credentials} onOpenChange={(open) => !open && setCredentials(null)}><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.credentials}><Dialog.Title><Check size={22} /> Client access created</Dialog.Title><Dialog.Description>{credentials?.details}</Dialog.Description><Dialog.Close className={styles.close} aria-label="Close credentials"><X size={18} /></Dialog.Close><div><span>Client ID</span><strong>{credentials?.clientId}</strong></div><div><span>Temporary password</span><strong>{credentials?.temporaryPassword}</strong></div><p>Share these details securely. The client must set a strong password on first login.</p></Dialog.Content></Dialog.Portal></Dialog.Root>
  </div>;
}
