"use client";
import { useState, useTransition, type FormEvent } from "react";
import { Check, Clock3, RefreshCcw, Save, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { adminStudioSettingOptions, adminStudioSettings, type AdminStudioSettings } from "@/lib/mocks/admin-settings";
import styles from "./admin-settings-workspace.module.css";

export function AdminSettingsWorkspace({ initialSettings, saveSettingsAction }: { initialSettings?: AdminStudioSettings; saveSettingsAction?: (input: AdminStudioSettings) => Promise<void> }) {
  const initial = initialSettings ?? adminStudioSettings;
  const [settings, setSettings] = useState(initial); const [saved, setSaved] = useState(initial); const [message, setMessage] = useState("Live rules loaded."); const [pending, startTransition] = useTransition();
  const dirty = JSON.stringify(settings) !== JSON.stringify(saved);
  function update<K extends keyof AdminStudioSettings>(key: K, value: AdminStudioSettings[K]) { setSettings((current) => ({ ...current, [key]: value })); }
  function submit(event: FormEvent) { event.preventDefault(); setMessage(""); startTransition(async () => { try { await saveSettingsAction?.(settings); setSaved(settings); setMessage("Studio rules saved."); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Could not save studio settings."); } }); }
  return <form className={styles.page} onSubmit={submit} aria-busy={pending}>
    <header className={styles.hero}><div><span className={styles.kicker}>Studio rules</span><h1>Set the operating code.</h1><p>Identity, timing and booking defaults that every connected workflow must follow.</p></div><div><button type="button" className="mv-btn mv-btn-secondary" disabled={!dirty || pending} onClick={() => { setSettings(saved); setMessage("Saved rules restored."); }}><RefreshCcw size={16} /> Reset</button><button type="submit" className="mv-btn mv-btn-primary" disabled={!dirty || pending}><Save size={16} /> {pending ? "Saving…" : "Publish rules"}</button></div></header>
    <section className={styles.scoreboard}><article><span>Save state</span><strong>{dirty ? "Pending" : "Synced"}</strong><small>{message}</small></article><article><span>Base session</span><strong>{settings.defaultSessionLength}</strong><small>Default program duration</small></article><article><span>Intake lead</span><strong>{settings.intakeLeadTime}</strong><small>Before intake decisions</small></article><article className={styles.blackCard}><span>Waitlist mode</span><strong>{settings.overbookWaitlist ? "On" : "Off"}</strong><small>Managed overflow policy</small></article></section>
    <section className={styles.console}><div className={styles.forms}>
      <fieldset><legend><ShieldCheck size={18} /><span><strong>Studio identity</strong><small>Public support and operating identity.</small></span></legend><div className={styles.grid}><label>Studio name<input required value={settings.studioName} onChange={(e) => update("studioName", e.target.value)} /></label><label>Support email<input required type="email" value={settings.supportEmail} onChange={(e) => update("supportEmail", e.target.value)} /></label><label>Support phone<input value={settings.supportPhone} onChange={(e) => update("supportPhone", e.target.value)} /></label><label>Timezone<input required value={settings.timezone} onChange={(e) => update("timezone", e.target.value)} /></label></div></fieldset>
      <fieldset><legend><Clock3 size={18} /><span><strong>Operating rhythm</strong><small>Timing defaults for sessions and onboarding.</small></span></legend><div className={styles.grid}><label>Default session length<select value={settings.defaultSessionLength} onChange={(e) => update("defaultSessionLength", e.target.value)}>{adminStudioSettingOptions.sessionLengths.map((o) => <option key={o}>{o}</option>)}</select></label><label>Intake lead time<select value={settings.intakeLeadTime} onChange={(e) => update("intakeLeadTime", e.target.value)}>{adminStudioSettingOptions.intakeLeadTimes.map((o) => <option key={o}>{o}</option>)}</select></label><label>Cancellation window<select value={settings.cancellationWindow} onChange={(e) => update("cancellationWindow", e.target.value)}>{adminStudioSettingOptions.cancellationWindows.map((o) => <option key={o}>{o}</option>)}</select></label><label>Private-session buffer<select value={settings.privateSessionBuffer} onChange={(e) => update("privateSessionBuffer", e.target.value)}>{adminStudioSettingOptions.privateSessionBuffers.map((o) => <option key={o}>{o}</option>)}</select></label></div></fieldset>
      <fieldset><legend><SlidersHorizontal size={18} /><span><strong>Booking controls</strong><small>Rules that shape the calendar experience.</small></span></legend><div className={styles.grid}><label>Schedule starts on<select value={settings.scheduleStartDay} onChange={(e) => update("scheduleStartDay", e.target.value)}>{adminStudioSettingOptions.scheduleStartDays.map((o) => <option key={o}>{o}</option>)}</select></label><label className={styles.switch}><input type="checkbox" checked={settings.overbookWaitlist} onChange={(e) => update("overbookWaitlist", e.target.checked)} /><span><i /><strong>Allow managed waitlist overflow</strong><small>Enable pressure-mode booking beyond available seats.</small></span></label></div></fieldset>
    </div><aside className={styles.snapshot}><div><Check size={20} /><span><strong>Rules snapshot</strong><small>{dirty ? "Review edits before publishing." : "Database values are active."}</small></span></div><dl><div><dt>Studio</dt><dd>{settings.studioName}</dd></div><div><dt>Timezone</dt><dd>{settings.timezone}</dd></div><div><dt>Session</dt><dd>{settings.defaultSessionLength}</dd></div><div><dt>Cancellation</dt><dd>{settings.cancellationWindow}</dd></div><div><dt>Private buffer</dt><dd>{settings.privateSessionBuffer}</dd></div><div><dt>Week starts</dt><dd>{settings.scheduleStartDay}</dd></div></dl><p>{message}</p></aside></section>
  </form>;
}
