"use client";

import Link from "next/link";
import { useTransition } from "react";
import { useRouter } from "next/navigation";
import { markNotificationRead } from "@/app/actions/notifications";
import type { Database } from "@/lib/supabase/database.types";

type Notification = Pick<Database["public"]["Tables"]["Notification"]["Row"],
  "id" | "kind" | "status" | "title" | "body" | "href" | "sentAt" | "readAt">;

export function NotificationWorkspace({ notifications }: { notifications: Notification[] }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  return <div className="dashboard-page-stack">
    <section className="dashboard-page-heading"><div><div className="mv-eyebrow">Automated updates</div><h1>Notifications</h1><p>Session and membership reminders generated by the studio automation.</p></div></section>
    <section className="dashboard-panel dashboard-panel--dense">
      <div className="dashboard-panel__header"><div><h2>{notifications.filter(item => item.status !== "READ").length} unread</h2><p>{notifications.length} recent notifications</p></div></div>
      {notifications.length ? <div className="dashboard-summary-list">{notifications.map(item => <article className="dashboard-summary-row" key={item.id}>
        <div><strong>{item.title}</strong><span>{item.body}</span><small>{new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "Africa/Cairo" }).format(new Date(item.sentAt))} · {item.status === "READ" ? "Read" : "Unread"}</small></div>
        <div className="dashboard-row-actions">{item.href ? <Link className="mv-btn mv-btn-outline" href={item.href}>Open</Link> : null}{item.status !== "READ" ? <button className="mv-btn mv-btn-secondary" disabled={pending} onClick={() => startTransition(async () => { await markNotificationRead(item.id); router.refresh(); })}>Mark read</button> : null}</div>
      </article>)}</div> : <div className="dashboard-empty-state"><strong>No notifications yet</strong><p>Session and renewal reminders will appear here when they are due.</p></div>}
    </section>
  </div>;
}
